### ISSUE TITLE
Can see the underlying checkbox on Android Chrome

### ISSUE THREAD

**Issue by samuelli** [nuclei/material-toggle#3]
Screenshot: https://imgur.com/a/or9wi

**Comment by lukasoppermann** [comment]
Uii, thanks for letting me know, will try to solve this soon.

**Comment by lukasoppermann** [comment]
Hey @samuelli this actually means a rather big change of the structure, as I will need to hide the checkbox completely. I am currently working on it in the `v1` branch. 

Would you be willing to test it on this branch once I finished it?

**Comment by samuelli** [comment]
@lukasoppermann: have you tried `-webkit-appearance: none;`?

**Comment by lukasoppermann** [comment]
@samuelli no I didn't, but I would rather not use non-standard css. However in the current version I am working with `::before/::after` so I can not hide the `checkbox`. 

In the `v1` version I am working with separate elements for the visual parts, so I can set the checkbox opacity to 0.

**Comment by samuelli** [comment]
@lukasoppermann: is bower support going to come back?

**Comment by lukasoppermann** [comment]
Wasn't planned, but I can add it.

**Comment by lukasoppermann** [comment]
Sorry for the delay. Should be working now.
