### ISSUE TITLE
Missing bower dependency

### ISSUE THREAD

**Issue by samuelli** [nuclei/material-toggle#4]
Missing webcomponents as a dependency or dev dependency. This is used for the inline demo on webcomponents.org.

**Comment by lukasoppermann** [comment]
Thanks, since we are on v1 I think I we need the individual files. Last time I tried v1 was not really supported in the combined webcomponents js, or did that change @samuelli?

**Comment by samuelli** [comment]
Ah, yeah. I think the v1 combined polyfill isn't ready yet.

**Comment by lukasoppermann** [comment]
So what do you suggest? I am actually only including bower.json because of webcomponents.org. The need to include the polyfill is mentioned in the readme.md in the installation section.

Do you think adding this to the bower.json makes sense and if so why?

**Comment by samuelli** [comment]
I think adding it as a dev dependency makes sense. Typically, dependencies only needed for tests/demos are added as dev dependencies.

**Comment by lukasoppermann** [comment]
Okay, I will add the 3 v1 polyfills.
